# PersonalMentor — Content Sources

rss_feeds:
- url: https://www.technologyreview.com/feed/
  category: tech
- url: https://hnrss.org/frontpage
  category: tech
- url: https://techcrunch.com/feed/
  category: tech
- url: https://feeds.bloomberg.com/technology/news.rss
  category: news
- url: https://ethz.ch/en/news-and-events/events.html
  category: news
  type: html
job_boards:
# Hitachi (primary target company) — Zurich area
- url: https://www.datacareer.ch/jobs/?q=Hitachi&location=Zurich
  type: html
  site: datacareer
  search_terms:
  - Hitachi
  - energy
  - AI
# SwissDevJobs (broad RSS, filtered by keywords + Zurich)
- url: https://swissdevjobs.ch/rss
  type: rss
  site: swissdevjobs
  filter_keywords:
  - Hitachi
  - AI
  - energy
  - economics
  - data
  - python
  - Zurich
  - Zürich
  # AI + Energy roles — Zurich area
- url: https://www.datacareer.ch/jobs/?q=AI+energy&location=Zurich
  type: html
  site: datacareer
  search_terms:
  - AI
  - energy
  - Hitachi
event_sources:
# AI events — Zurich area
- url: https://www.eventbrite.com/d/switzerland--zurich/artificial-intelligence/
  location_filter: ''
- url: https://www.meetup.com/find/?keywords=artificial+intelligence&location=ch--zurich&source=EVENTS
  location_filter: ''
# Energy events — Zurich area
- url: https://www.eventbrite.com/d/switzerland--zurich/energy-technology/
  location_filter: ''
# ETH Zurich events
- url: https://ethz.ch/en/news-and-events/events.html
  location_filter: ''
